-- Server-authoritative AI request limits. Safe to rerun on MariaDB 10.3+.
ALTER TABLE ai_requests ADD COLUMN IF NOT EXISTS request_id VARCHAR(80) NULL;
ALTER TABLE ai_requests ADD COLUMN IF NOT EXISTS idempotency_key VARCHAR(128) NULL;
ALTER TABLE ai_requests ADD COLUMN IF NOT EXISTS plan VARCHAR(32) NULL;
ALTER TABLE ai_requests ADD COLUMN IF NOT EXISTS is_photo BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE ai_requests ADD COLUMN IF NOT EXISTS period_date DATE NULL;
ALTER TABLE ai_requests ADD COLUMN IF NOT EXISTS error_code VARCHAR(64) NULL;
ALTER TABLE ai_requests ADD COLUMN IF NOT EXISTS duration_ms INT UNSIGNED NULL;
ALTER TABLE ai_requests ADD COLUMN IF NOT EXISTS estimated_cost_minor INT UNSIGNED NOT NULL DEFAULT 0;
CREATE TABLE IF NOT EXISTS ai_limit_locks (
  lock_key VARCHAR(128) NOT NULL PRIMARY KEY,
  touched_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
