param([string]$Root = (Split-Path -Parent $PSScriptRoot))

$utf8 = [System.Text.UTF8Encoding]::new($false)
$sha = [System.Security.Cryptography.SHA256]::Create()
$patternText = @'
Localized(?<kind>Selectable)?Text\(\s*(?<literal>'(?:\\.|[^'\\])*'|"(?:\\.|[^"\\])*")
'@
$pattern = [regex]::new($patternText.Trim())
$entries = @{}

foreach ($file in (Get-ChildItem (Join-Path $Root 'lib') -Recurse -Filter '*.dart')) {
  if ($file.Name -eq 'localized_text.dart') { continue }
  $text = [System.IO.File]::ReadAllText($file.FullName, $utf8)
  $updated = $pattern.Replace($text, {
    param($match)
    $literal = $match.Groups['literal'].Value
    if ($literal.Contains('$')) { return $match.Value }
    $after = $text.Substring($match.Index + $match.Length)
    if ($after -match "^\s*[`"']") { return $match.Value }
    $hash = [System.BitConverter]::ToString(
      $sha.ComputeHash($utf8.GetBytes($literal))
    ).Replace('-', '').Substring(0, 12).ToLowerInvariant()
    $key = "ui.text.$hash"
    $entries[$key] = $literal
    return $match.Value.Substring(0, $match.Groups['literal'].Index - $match.Index) +
      "'$key'"
  })
  if ($updated -ne $text) {
    [System.IO.File]::WriteAllText($file.FullName, $updated, $utf8)
    Write-Output "updated $($file.FullName.Substring($Root.Length + 1))"
  }
}

$lines = @(
  '// Generated by tool/migrate_localized_text_keys.ps1.',
  '// Stable UI keys mapped to source phrases so existing 30-language translations are preserved.',
  'const uiKeySources = <String, String>{'
)
foreach ($key in ($entries.Keys | Sort-Object)) {
  $lines += "  '$key': $($entries[$key]),"
}
$lines += '};'
[System.IO.File]::WriteAllText(
  (Join-Path $Root 'lib\l10n\ui_key_sources.dart'),
  ($lines -join "`r`n") + "`r`n",
  $utf8
)
Write-Output "keys $($entries.Count)"
